# Generated by Django 5.0.2 on 2024-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
