# Generated by Django 5.0.2 on 2024-03-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
